spring.application.name=ticketRush
spring.datasource.url=jdbc:mysql://localhost:3306/testRush
spring.datasource.username=root
spring.datasource.password=MatKhauCuaBan123!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate (nếu dùng JPA)
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true