spring.application.name=ticketRush
server.port=8082
spring.datasource.url=jdbc:mysql://localhost:3306/testrush
spring.datasource.username=root
spring.datasource.password=1
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
app.frontend.url=http://localhost:5173
# Hibernate (nếu dùng JPA)
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
# Keycloak
spring.security.oauth2.client.registration.ticketRush.client-id=TicketRush_Client
#spring.security.oauth2.client.registration.ticketRush.client-secret=HIb3ONXifdqpwnljMLLzG3uehLRVjTav
#spring.security.oauth2.client.registration.ticketRush.client-secret=6EdiEgo8KUtj18n8cVfTxt2MfnUoC0KN
spring.security.oauth2.client.registration.ticketRush.scope=openid,profile,roles,email
spring.security.oauth2.client.registration.ticketRush.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.ticketRush.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.provider.ticketRush.issuer-uri=http://localhost:8080/realms/TicketRush